sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
  - pypy3
  - "nightly"

install:
 - pip install -U pip
 - pip install -U wheel setuptools pbr
 - pip install -U testtools docutils
 - pip list
 - python --version

script:
 - make check
 - rst2html.py --strict README.rst README.html
